### ISSUE TITLE
Publishing Report fails on Windows(64) ?

### ISSUE THREAD

**Issue by psarras** [stryker-mutator/azure-devops-mutationreport-publisher#1271]
I have problem uploading the report of the mutation testing into DevOps.

![Image](https://github.com/user-attachments/assets/e09499ac-9bed-4fee-be0f-b51be2d41c13)

The reason is that no reports were uploaded. The step of uploading fails with the following error message, pointing to the operating system **current operating system 'Windows(X64)'**.

```
Starting: Publish Mutation Test Report
==============================================================================
Task         : Publish Mutation Test Report
Description  : Use this task to upload your mutation test report to your build result.
Version      : 2.0.0
Author       : Rouke Broersma
Help         : [More Information](https://github.com/stryker-mutator/azure-devops-mutationreport-publisher)
==============================================================================
##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.
Finishing: Publish Mutation Test Report
```

stryker worked correctly:

![Image](https://github.com/user-attachments/assets/d882f526-aa01-4e6c-b659-07855f5dc161)

with this in the pipeline

```yaml
  - powershell: |
      dotnet tool install --global dotnet-stryker
    displayName: Install Stryker
    failOnStderr: false

  - powershell: |
      dotnet stryker -s AdSecCore.sln --test-project AdSecCoreTests/AdSecCoreTests.csproj -l basic
    displayName: Run Stryker
    failOnStderr: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Stryker Mutation Report'
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/StrykerOutput'
      artifactName: 'StrykerReport'
  
  - task: PublishMutationReport@2
    displayName: 'Publish Mutation Test Report'
    inputs:
      reportPattern: '**/mutation-report.html'
      reportDisplayName: 'Mutation Report'
```

and we are using this stryker-config

```
{
  "stryker-config": {
    "reporters": [
      "html",
      "progress"
    ],
    "since": {
      "target": "origin/main"
    }
  }
}
```

I think the diff, is not a problem, as I added it later. I am also uploading the artifact and this part worked correctly showing an html on the artifacts located at: ``
