### ISSUE TITLE
Report tab not loading on Azure devops server

### ISSUE THREAD

**Issue by danielmertens** [stryker-mutator/azure-devops-mutationreport-publisher#176]
I'm attempting to use this plugin on our Azure devops server but the report tab seems to be infinitely loading when I open it.
I have included my Yaml pipeline (Stryker is running with correct output and the file is generated) and some logs from the Chrome Developers Console. This last one seems to contain an error.

### Versions
 - dotnet-stryker: 0.20.0
 - azure-devops-mutationreport-publisher: 0.1.3

### Yaml

```
- task: DotNetCoreCLI@2
    displayName: 'Install dotnet-stryker'
    inputs:
      command: custom
      custom: tool
      arguments: update dotnet-stryker --tool-path $(Agent.ToolsDirectory)

  - task: Powershell@2
    displayName: 'Run mutation test on ${{ parameters.testName}}'
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      targetType: 'inline'
      script: $(Agent.ToolsDirectory)/dotnet-stryker ${{ parameters.strykerCommands}}

  - task: PublishMutationReport@0
    displayName: 'Publish Mutation Test Report'
    inputs:
      reportPattern: '**/mutation-report.html'
```

### Developer console
![image](https://user-images.githubusercontent.com/17334508/96706985-95d9cb00-1397-11eb-9c24-6afc2a094ca7.png)

I can confirm, by using the diagnostic logs, that the html file is found and uploaded by the task.
