### ISSUE TITLE
Report does not load in Azure Dev Ops 

### ISSUE THREAD

**Issue by whatisthejava** [stryker-mutator/azure-devops-mutationreport-publisher#37]
Hi, followed the instructions as outlined on the blog and installed the plug in but my build is reporting 0 artifacts 

Have a run stryker task 

steps:
- task: DotNetCoreCLI@2
  displayName: 'Stryker - Project'
  inputs:
    command: custom
    custom: 'stryker '
    arguments: '-im [''GetHashCode''] -r "[''html'']" -th 90 -tl 80 -tb 50'
    workingDirectory: 'project.Test'

This works and logs as expected 

Second task 
steps:
- task: stryker-mutator.mutation-report-publisher.44d9cfb7-7efd-48e2-b2ae-4750950271be.PublishMutationReport@0
  displayName: 'Publish Mutation Test Report'
  inputs:
    reportPattern: 'project.Test/**/*.html'

The publish tasks completes without error but no artifact is created and no extra tab displays.
Do i also need to publish this artifact as a final step 

Thanks

**Comment by Mobrockers** [comment]
Do you use a (multi-stage) YAML pipeline? If so I have noticed the same thing #32

**Comment by robertlarkins** [comment]
I'm getting the same thing in Azure DevOps when using dotnet core 3.1 with dotnet-stryker installed as local tool in the test project. This is my yaml code:
```yaml
  - script: dotnet tool restore
    workingDirectory: 'tests/domain/Company.Product.Domain.Tests.Unit'
    displayName: 'Install dotnet tools for Stryker.CLI'

  - script: dotnet tool run dotnet-stryker -tr dotnettest -r "['cleartext', 'html', 'progress']" --solution-path "../../../Company.Product.sln"
    workingDirectory: 'tests/domain/Company.Product.Domain.Tests.Unit'
    displayName: 'Run Stryker on solution'

  - task: PublishMutationReport@0
    inputs:
      reportPattern: '$(Build.SourcesDirectory)/tests/domain/Company.Product.Domain.Tests.Unit/StrykerOutput/*/reports/mutation-report.html'
```
This is a single job pipeline so isn't multi-stage.
